apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - '/etc/prometheus/rules/*.rules'

    alerting:
      alertmanagers:
      - static_configs:
          - targets: ['alertmanager:9093']

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus:9090']

      - job_name: 'node_exporter'
        scrape_interval: 5s
        static_configs:
          - targets: ['node-exporter:9100']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtpAddress:25'                                #Please enter the SMTP address.
      smtp_from: 'GRAFANA-ALERTMANAGER <senderEmailAddress>'          #Please enter the sender's email address
      smtp_auth_username: 'senderEmailUsername'                       #Enter the username for the sender email address.
      smtp_auth_password: 'senderEmailPassword'                       #Enter the password for the sender email address.
      smtp_require_tls: false

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 3m
      repeat_interval: 30m
      receiver: 'email-notifications'

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'recipientEmailAddress'                                 #Enter the recipient email address. If there are multiple recipients, separate them with a comma.
